# Generated by Django 5.0.6 on 2026-10-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
